server:
  port: 8081
  ssl:
    enabled: false

service:

  solrService:
    zkEnsembleDestination : freshdapp01v2.ftdi.com:2181

  productService:
    baseUrl: http://35.227.193.133/siteId/api/products

  pricingService:
    baseUrl: http://35.227.252.218/siteId/api/pricing

  metrics:
    prometheus:
      enabled: false
    dropwizard:
      enabled: false
    jmx:
      enabled: false
  swagger:
    enabled: false
  git:
    enabled: false

  pubsub:
    productSubscription: search.product.update.dev.dev1.local
    pricingSubscription: search.pricing.update.dev.dev1.local
    productDeleteSubscription: search.product.delete.dev.dev1.local

  autofill:
    enabled: false