server:
  port: 443
  ssl:
    key-store: "classpath:keystore.jks"
    key-store-password: changeit
    enabled: true
  http:
    port: 80


spring:
  application:
    name: search-listener
  profiles:
    active: local
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    default-property-inclusion: non_null
  cloud:
    config:
      allow-override: true
      override-none: false
      fail-fast: true
      override-system-properties: false
      enabled: false
  sleuth:
    web:
      enabled: true
    sampler:
      percentage: 100
  zipkin:
    base-url: http://localhost:8680/
    flush-interval: 15
    enabled: false

  cloud:
    gcp:
      credentials:
        project-id: quality-assurance-191019


service:
  # kafka configuration
  kafka:
    enabled: false
    bootstrapServers: freshdapp01v1.ftdi.com:9092
    groupId: indexers
    productTopics: product
    productDeleteTopics: productDelete
    inventoryTopics: inventory
    priceTopics: price
    failureTopic: failure
    productGroup: productGroup
    productDeleteGroup: productDeleteGroup
    inventoryGroup: inventoryGroup
    priceGroup: priceGroup

    concurrency : 3
    maxRetryAttempts : 3
    retryInterval : 1000


  # pub-sub configuration
  pubsub:
    enabled: true
    productSubscription: search.product.update.${spring.profiles.active}.${spring.profiles.active}
    pricingSubscription: search.pricing.update.${spring.profiles.active}.${spring.profiles.active}
    productDeleteSubscription: search.product.delete.${spring.profiles.active}.${spring.profiles.active}
    failureTopic: search.failure.${spring.profiles.active}
    productChannelName: pubsubInputProductChannel
    pricingChannelName: pubsubInputPriceChannel
    productDeleteChannelName: pubsubInputProductDeleteChannel
    failureChannelName: pubsubOutputFailureChannel

  # PIM service configuration
  pimService:
    baseUrl: "https://apiservice.providecommerce.com/API/Product/v1/JSON/GetProductDetail"
    accessToken: abcd
    apolloBaseUrl: "http://amsdapp01v1.ftdi.com:8700/prodinfo/products"

  solrService:
    enabled: true
    zkEnsembleDestination : zk-${spring.profiles.active}-0.zk-hs-${spring.profiles.active}.${spring.profiles.active}.svc.cluster.local:2181,zk-${spring.profiles.active}-1.zk-hs-${spring.profiles.active}.${spring.profiles.active}.svc.cluster.local:2181,zk-${spring.profiles.active}-2.zk-hs-${spring.profiles.active}.${spring.profiles.active}.svc.cluster.local:2181

    collectionDestination : products
    zkTimeoutDestination : 20000
    queryTimeout : 10000
    maxRetryAttempts: 3
    retryInterval: 500


  productService:
    enabled: true
    baseUrl: http://product-service/siteId/api/products
    version: 0

  pricingService:
    enabled: true
    baseUrl: http://pricing-service/siteId/api/pricing
    version: 0


  # BSO Configuration
  bso:
    enabled: true
    fileReloadRate: 86400000
#    file: /Users/vsekhri/Desktop/product_margin_feed.csv
    file: gs://us.artifacts.deep-thought-185318.appspot.com/product_margin_feed.csv

#  sitesBsoMap:
#    proflowers: /Users/vsekhri/Documents/FTD-Local/probsofile.prn
#    ftd: /Users/vsekhri/Documents/FTD-Local/probsofile.prn

  # Autofill Configuration
  autofill:
    enabled: true
    keywordReloadRate: 86400000
    querySize: 3
    keywordsFile:
      proflowers: gs://us.artifacts.deep-thought-185318.appspot.com/ftd_top_keywords.txt
      ftd: gs://us.artifacts.deep-thought-185318.appspot.com/ftd_top_keywords.txt

  sitesAutofillKeywordMap:
#    proflowers: /Users/vsekhri/src/search-listener/src/main/resources/ftd_top_keywords.txt
#    ftd: /Users/vsekhri/src/search-listener/src/main/resources/ftd_top_keywords.txt
    proflowers: gs://us.artifacts.deep-thought-185318.appspot.com/ftd_top_keywords.txt
    ftd: gs://us.artifacts.deep-thought-185318.appspot.com/ftd_top_keywords.txt


  metrics:
    dropwizard:
      enabled: true
    prometheus:
      enabled: true
  git:
    enabled: false
  swagger:
    enabled: true
#    base-package: productGroup
  logging:
    enabled: true
  https:
    enabled: true

logging:
  level:
    ROOT: INFO
