server:
  context-path: /${spring.application.name}
  port: 8080

spring:
  application:
    name: generic-search-listener
  profiles:
    active: local
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    default-property-inclusion: non_null
  cloud:
    config:
      allow-override: true
      override-none: false
      fail-fast: true
      override-system-properties: false
      enabled: false
  sleuth:
    web:
      enabled: true
    sampler:
      percentage: 100
  zipkin:
    base-url: http://localhost:8680/
    flush-interval: 15
    enabled: false


service:
  zkEnsembleDestination : freshdapp01v1.ftdi.com:2181
  collectionDestination : products
  zkTimeoutDestination : 20000
  solrQueryTimeout : 10000
  queryTimeAllowed : 10000


  kafkaBootstrapServers: freshdapp01v1.ftdi.com:9092
  kafkaGroupId: indexers
  kafkaProductTopics: product
  kafkaInventoryTopics: inventory
  kafkaPriceTopics: price
  kafkaProductGroup: productGroup
  kafkaInventoryGroup: inventoryGroup
  kafkaPriceGroup: priceGroup

  kafkaConcurrency : 3
  kafkaMaxRetryAttempts : 3
  kafkaRetryInterval : 1000
  solrMaxRetryAttempts : 5
  solrRetryInterval : 500
  pimService:
    baseUrl: "https://apiservice.providecommerce.com/API/Product/v1/JSON/GetProductDetail"
    accessToken: abcd

  metrics:
    dropwizard:
      enabled: true
    prometheus:
      enabled: true
  git:
    enabled: true
  vip:
    enabled: true
  swagger:
    enabled: true
  logging:
    enabled: true


management:
  security:
    enabled: false