server:
  port: 8081
  ssl:
    enabled: false

service:
  metrics:
    prometheus:
      enabled: false
    dropwizard:
      enabled: false
    jmx:
      enabled: false
  swagger:
    enabled: false
  git:
    enabled: false

  pubsub:
    productSubscription: search.product.update.dev.dev1.local
    pricingSubscription: search.pricing.update.dev.dev1.local
    productDeleteSubscription: search.product.delete.dev.dev1.local

  autofill:
    enabled: true