server:
  port: 8081
  ssl:
    enabled: false


spring:
  cloud:
    gcp:
      pubsub:
#        project-id: sandbox-191019
        credentials:
          location: file:/users/vsekhri/apps/gcp/Quality Assurance-88570982a040.json


service:

  solrService:
    zkEnsembleDestination : freshdapp01v2.ftdi.com:2181

  productService:
    baseUrl: http://gcp-nonprod1-dev1-proxy.ftdi.com/product-service/siteId/api/products

  pricingService:
    baseUrl: http://gcp-nonprod1-dev1-proxy.ftdi.com/pricing-service/siteId/api/pricing

  metrics:
    prometheus:
      enabled: false
    dropwizard:
      enabled: false
    jmx:
      enabled: false
  swagger:
    enabled: false
  git:
    enabled: false

  pubsub:
    productSubscription: nonprod1.dev1.search.product.update.local
    pricingSubscription: nonprod1.dev1.search.product.update.local
    productDeleteSubscription: nonprod1.dev1.search.product.delete.local

  autofill:
    enabled: false