---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: search-listener-service-group
spec:
  selector:
    matchLabels:
      app: search-listener
      ns: group
  maxUnavailable: 1