---
apiVersion: v1
kind: Service
metadata:
  name: search-listener-service-group
  labels:
    app: search-listener
spec:
  ports:
  - port: 8080
    name: server
  selector:
    app: search-listener
  type: NodePort