---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: search-listener-service-group
  labels:
    app: search-listener
    ns: group
spec:
  selector:
    matchLabels:
      app: search-listener
      ns: group
  replicas: 1
  template:
    metadata:
      labels:
        app: search-listener
        ns: group
    spec:
      containers:
      - name: search-listener-service
        imagePullPolicy: Always
        image: "gcr.io/deep-thought-185318/search-listener-service:e6b8b6fdce964f0b2c0aaecf9256d16fdfc6bfc8"
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.5"
        ports:
        - containerPort: 8080
          name: server
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "group"
        - name: SERVICE_SOLRSERVICE_ZKENSEMBLEDESTINATION
          value: "zk-group-0.zk-hs-group.default.svc.cluster.local:2181,zk-group-1.zk-hs-group.default.svc.cluster.local:2181,zk-group-2.zk-hs-group.default.svc.cluster.local:2181"
        - name: SERVICE_PRODUCTSERVICE_BASEURL
          value: "http://product-service-group/api/products"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 65
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10