---
apiVersion: v1
kind: Service
metadata:
  name: search-listener-service-group
  labels:
    app: search-listener
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  selector:
    app: search-listener
    ns: group
  type: ClusterIP