---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: search-listener-deployment
  labels:
    app: search-listener
spec:
  selector:
    matchLabels:
      app: search-listener
  replicas: 3
  template:
    metadata:
      labels:
        app: search-listener
    spec:
      containers:
      - name: search-listener
        imagePullPolicy: Always
        image: "sekhrivijay/search-listener:10936516e4a5452580543a3b1427adc694526a86"
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.5"
        ports:
        - containerPort: 8080
          name: server
        env:
        - name: SERVICE_ZKENSEMBLEDESTINATION
          value: "zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181"
        - name: SERVICE_KAFKABOOTSTRAPSERVERS
          value: "freshdapp01v1.ftdi.com:9092"

#        command:
#        - java
#        - "-Dservice.zkEnsembleDestination=zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181"
#        - "-Dservice.kafkaBootstrapServers=freshdapp01v1.ftdi.com:9092"
#        - -jar
#        - search-listener-1.0-SNAPSHOT.jar
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 55
          periodSeconds: 10
